name: Test PR

on: 
    workflow_dispatch:

jobs:
  testpr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - id: branchname
        run: echo "branchname=testpr_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - run: |
          echo $(date) > test.txt
          git switch -c ${{ steps.branchname.outputs.branchname }}
          git config user.name hoge
          git config user.email hoge@hogehoge.hoge
          git add .
          git commit -m 'Update subgraph schemas'
          git push origin ${{ steps.branchname.outputs.branchname }}
          PR_NUMBER=$(gh pr create -B main -t 'Update schema $(date +'%Y%m%d%H%M%S')' -b '' -H ${{ steps.branchname.outputs.branchname }} | awk -F '/' '{ print $7 }')
          gh pr merge -m --auto $PR_NUMBER
        env:
          GH_TOKEN: ${{ github.token }}



    


